//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionDeGestion.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.06")]
        public float precioParking {
            get {
                return ((float)(this["precioParking"]));
            }
            set {
                this["precioParking"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NTY2OTI3QDMxMzkyZTM0MmUzMG85Q0toWFI2U2dGcVIwdjlXRHBDVGlHanpxZFlWVEJLcnZWUWtuSE5Ee" +
            "kU9")]
        public string licenciaSyncfusion {
            get {
                return ((string)(this["licenciaSyncfusion"]));
            }
            set {
                this["licenciaSyncfusion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DefaultEndpointsProtocol=https;AccountName=juegopeliculasjuandi;AccountKey=55hpkg" +
            "qMOrvwuZDsxLmMr/l78pZCJJxaBLDQtIBWFzFKsSuHjS7i/TNpWyXVnJu7wiozsjwVpeOQtfty3asRzQ" +
            "==;EndpointSuffix=core.windows.net")]
        public string cadenaConexionBlobStorage {
            get {
                return ((string)(this["cadenaConexionBlobStorage"]));
            }
            set {
                this["cadenaConexionBlobStorage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("imagenes-peliculas")]
        public string nombreContenedorBlob {
            get {
                return ((string)(this["nombreContenedorBlob"]));
            }
            set {
                this["nombreContenedorBlob"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:/parking/")]
        public string rutaConexionBd {
            get {
                return ((string)(this["rutaConexionBd"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://servicioface.cognitiveservices.azure.com/")]
        public string endpointFace {
            get {
                return ((string)(this["endpointFace"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("495d5808afaa455c860b5f8b52f5c22e")]
        public string keyFace {
            get {
                return ((string)(this["keyFace"]));
            }
        }
    }
}
